spring:
  profiles:
    group:
      'local':
        - local-server
        - debug-logging
        - enabled-swagger
      'test':
        - local-server
        - debug-logging
        - disabled-swagger
