gemini:
  key: ${GEMINI_API_KEY}
  models:
    flash: gemini-2.5-flash
    flash-lite: gemini-2.5-flash-lite

open-router:
  key: ${OPEN_ROUTER_API_KEY}
  models:
    nvidia-nemotron: nvidia/nemotron-3-nano-30b-a3b:free
