[versions]
kotlin = "2.2.21"
spring-boot = "4.0.0"
spring-dependency-management = "1.1.7"
ktlint = "14.0.1"
java = "21"

kotlin-logging = "3.0.5"
jjwt = "0.13.0"

[libraries]
# Spring Boot
spring-boot-webmvc = { module = "org.springframework.boot:spring-boot-starter-webmvc" }
spring-boot-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-boot-devtools = { module = "org.springframework.boot:spring-boot-devtools" }
spring-boot-config-processor = { module = "org.springframework.boot:spring-boot-configuration-processor" }
spring-boot-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-webmvc-test = { module = "org.springframework.boot:spring-boot-starter-webmvc-test" }

# Spring Security
spring-security-config = { module = "org.springframework.security:spring-security-config" }

# Kotlin
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5" }

# Jackson
jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin" }

# Logging
kotlin-logging = { module = "io.github.microutils:kotlin-logging-jvm", version.ref = "kotlin-logging" }

# JWT
jjwt-api = { module = "io.jsonwebtoken:jjwt-api", version.ref = "jjwt" }
jjwt-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jjwt" }
jjwt-jackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jjwt" }

# Test runtime
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

[bundles]
spring-boot-web = [
  "spring-boot-webmvc",
  "spring-boot-security",
  "spring-security-config"
]

kotlin-core = [
  "kotlin-reflect"
]

serialization = [
  "jackson-kotlin"
]

logging = [
  "kotlin-logging"
]

jwt = [
  "jjwt-api"
]

spring-boot-test = [
  "spring-boot-test",
  "spring-boot-webmvc-test",
  "kotlin-test-junit5",
  "junit-platform-launcher"
]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }

spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }

ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
